### PR TITLE
Code clean up with BitVector maintaining position

### PR DESCRIPTION
**Pull request by evanwht**
Hi @SleimanJneidi.

I took a stab at cleaning up the code to make it more readable and improving the parsing speed by a small margin. I took inspiration from laktech's comments on the PR you opened for the iab's repo but decided against defining offsets for each field as there are fields that can't have a statically defined offset. Moving the offsets to a position maintained by the bit vector cleaned up a lot of the decoding code. I also used builders for each object being created with slightly revised names. Lastly, I cleaned up the package structure and corrected the visibility of certain classes and interfaces so users of this library won't have access to implementation details. The package structure will most likely have to change again once encoding is done and when someone adds the GVl model back in. 

Also, I added support to parse more than 3 segments as the TCF spec shows there are up to 4 segments that will be passed.

### CODE REVIEW

**Comment by evanwht** [comment]
Made a final commit to remove the BitSet in BitVector and instead read directly from the byte array. That resulted in another (10-20%) improvement in decoding speed.

**Comment by SleimanJneidi** [comment]
@evanwht1 bitsets are more memory efficient though? Could you create a gist of the benchmark please.

**Comment by evanwht** [comment]
We've already created the byte array that the bit set is built off of so my change doesn't create any new garbage. Since this doesn't do any lazy decoding, the byte array only lives around long enough to decode the string, then gets garbage collected. I've been using jmh to benchmark by calling TCModelDecoder.decode() with this consent string 

> "COukWFXOukWFXLnACAENAPCIAKAAAKAAACiQFoQAQALgWhABAAuAAA.IFoEUQQgAIQwgIwQABAEAAAAOIAACAIAAAAQAIAgEAACEAAAAAgAQBAAAAAAAGBAAgAAAAAAAFAAECAAAgAAQARAEQAAAAAJAAIAAgAAAYQEAAAQmAgBC3ZAYzUw.QEUwAQALgA"

**Comment by evanwht** [comment]
@SleimanJneidi Just to be clear, this is not on top of your single-scan branch. This still uses the String.split() and DECODER.decode() logic which already builds a byte[]. Since that is the case, using the byte array directly in BitVector is more memory efficient as each byte fully represents 8 bits.

**Pull request closed without merging**
